# Generated by Django 5.0.4 on 2024-05-17 23:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_remove_user_username_destination_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numberOfPeople', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('totalPrice', models.IntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('reservationDate', models.DateField()),
                ('cancelled', models.BooleanField(default=False)),
                ('idDestination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.destination')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.user')),
            ],
        ),
    ]
